services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: borges
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
